"""Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms."""

def fibonacci():
    a1 = 0
    a2 = 1
    soma = 0
    prox = 0
    while prox < 4000000:
      if prox % 2 == 0:
          soma += prox
      prox = a1 + a2
      a1 = a2
      a2 = prox
      if prox > 4000000:
          return soma

      print(f'{a1}')
      
def test_fibonacci():
    assert fibonacci() == 4613732

if __name__ == '__main__':
    k = fibonacci()
    print('A soma é =', k)

     






